[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  command = "npm run start:ci"
  functions = "./functions"
  publish = "dist/dylanbonneau"
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"